edition = "2018" # default: 2015
enum_discrim_align_threshold = 30
format_code_in_doc_comments = true 
format_macro_matchers = true 
format_strings = true
imports_indent = "Visual"
indent_style = "Visual"
license_template_path = ".license.template"
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 30
struct_lit_single_line = false
trailing_comma = "Never"
unstable_features = true
use_field_init_shorthand = false
use_try_shorthand = true
where_single_line = true
wrap_comments = true